### ISSUE TITLE
New crash

### ISSUE THREAD

**Issue by alaaghribi** [syshen/FlatDatePicker#13]
Hi,
I wanted to test FlatDatePicker, so I downloaded the demo project and run it, however, I'm facing that problem/crash:

![screen shot 2014-03-19 at 10 56 31](https://f.cloud.github.com/assets/2395568/2458467/868e55dc-af4c-11e3-943f-48ba55e64e30.png)
Can you please take an urgent look on it?
Thank you.

**Comment by syshen** [comment]
fixed
